apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-site-deployment
  labels:
    app: web-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-site
  template:
    metadata:
      labels:
        app: web-site
    spec:
      containers:
      - name: web-site
        image: "{IMAGE}"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-site-service
spec:
  selector:
    app: web-site
  ports:
  - port: 80
    protocol: TCP
