apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-product-deployment
  labels:
    app: api-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-product
  template:
    metadata:
      labels:
        app: api-product
    spec:
      containers:
      - name: api-product
        image: "{IMAGE}"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-product-service
spec:
  selector:
    app: api-product
  ports:
  - port: 80
    protocol: TCP
